### ISSUE TITLE
chore: add automated store submission after release

### ISSUE THREAD

**Issue by ryo-morimoto** [ryo-morimoto/lara-ver#109]
## Overview
Enhance the automated release workflow to automatically submit the extension to Chrome Web Store and Firefox Add-ons after a successful release.

## Current State
The release workflow currently:
- ✅ Automatically creates releases on main branch merge
- ✅ Builds extension packages for Chrome and Firefox
- ❌ Requires manual submission to extension stores

## Proposed Enhancement
Uncomment and implement the store submission steps in `.github/workflows/release.yml` (lines 116-130):

```yaml
# Future: Auto-submit to stores (requires secrets setup)
- name: Submit to Chrome Web Store
  run: pnpm wxt submit --chrome --dry-run
  env:
    CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
    CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
    CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
    CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

- name: Submit to Firefox Add-ons
  run: pnpm wxt submit --firefox --dry-run
  env:
    FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
    FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
    FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
```

## Required Secrets
The following GitHub repository secrets need to be configured:

### Chrome Web Store
- `CHROME_EXTENSION_ID`: Extension ID from Chrome Web Store
- `CHROME_CLIENT_ID`: OAuth2 client ID
- `CHROME_CLIENT_SECRET`: OAuth2 client secret
- `CHROME_REFRESH_TOKEN`: OAuth2 refresh token

### Firefox Add-ons
- `FIREFOX_EXTENSION_ID`: Extension ID from Firefox Add-ons
- `FIREFOX_JWT_ISSUER`: JWT issuer (API key)
- `FIREFOX_JWT_SECRET`: JWT secret

## Implementation Steps
1. [ ] Obtain API credentials for Chrome Web Store
2. [ ] Obtain API credentials for Firefox Add-ons
3. [ ] Add secrets to GitHub repository settings
4. [ ] Remove `--dry-run` flags after testing
5. [ ] Add conditional logic to only submit on successful release
6. [ ] Add error handling and notifications for failed submissions

## Benefits
- Fully automated release pipeline from code to store
- Reduced manual work and human error
- Faster delivery of updates to users
- Consistent release process

## References
- [WXT Submit Documentation](https://wxt.dev/guide/submit.html)
- [Chrome Web Store API](https://developer.chrome.com/docs/webstore/using_webstore_api/)
- [Firefox Add-ons API](https://extensionworkshop.com/documentation/develop/web-ext-command-reference/#web-ext-sign)
