### ISSUE TITLE
ci: プルリクエストでの自動テスト実行

### ISSUE THREAD

**Issue by ryo-morimoto** [ryo-morimoto/lara-ver#80]
## 概要
プルリクエスト時に自動でlint、typecheck、unit testを実行するGitHub Actionsワークフローを作成する。

## 実装タスク
- [ ] `.github/workflows/test.yml`の作成
- [ ] Node.js環境のセットアップ
- [ ] pnpm環境のセットアップ
- [ ] `pnpm lint`の実行
- [ ] `pnpm compile`の実行  
- [ ] `pnpm test`の実行
- [ ] 失敗時の適切なエラー報告

## ワークフロー例
```yaml
name: Test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm compile
      - run: pnpm test
```

## 成果物
- PRでの自動テスト実行
- テスト結果のPRコメント表示
