### ISSUE TITLE
ci: リリース時の自動ビルド・パッケージング

### ISSUE THREAD

**Issue by ryo-morimoto** [ryo-morimoto/lara-ver#81]
## 概要
タグプッシュ時に自動でビルドし、Chrome/Firefox用のzipファイルを生成してGitHub Releasesにアップロードする。

## 実装タスク
- [ ] `.github/workflows/release.yml`の作成
- [ ] タグプッシュをトリガーとする設定
- [ ] 拡張機能のビルド実行
- [ ] Chrome/Firefox用zipファイルの生成
- [ ] GitHub Releasesへの自動アップロード
- [ ] リリースノートの自動生成

## 依存関係
- Issue #80 (プルリクエスト自動テスト) が完了していること

## ワークフロー例
```yaml
name: Release
on:
  push:
    tags: ['v*']
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - # ビルド処理
      - run: pnpm zip
      - run: pnpm zip:firefox
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            .output/*.zip
```

## 成果物
- 自動生成されたzipファイル
- GitHub Releases
